version: '2'
 
services:
    jenkins:
      image: jenkins/jenkins
      container_name: jenkins
      hostname: jenkins01
      restart: always
      network_mode: "bridge"
      ports:
        - "8080:8080"
        - "50000:50000"
 
    gitlab:
        image: gitlab/gitlab-ce
        container_name: gitlab
        hostname: gitlab
        restart: always
        network_mode: bridge
        ports:
           - "443:443"
           - "80:80"
           - "22:22"
       
    cadvisor:
        image: google/cadvisor
        container_name: cadvisor
        ports:
           - 8082:8080
        volumes:
           - /:/rootfs:ro
           - /var/run:/var/run:rw
           - /sys:/sys:ro
           - /var/lib/docker:/var/lib/docker:ro

    metrics-gateway:
        container_name: metrics-gateway
        image: prom/pushgateway
        ports:
           - 9091:9091

    prometheus-server:
        image: prom/prometheus
        container_name: prometheus
        ports:
           - 9090:9090
        links:
           - cadvisor:cadvisor
           - metrics-gateway:metrics-gateway
           - node-exporter:node-exporter
        volumes:
           - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

    node-exporter:
        image: prom/node-exporter
        ports:
            - '9100:9100'
     
    grafana-ui:
        image: grafana/grafana
        container_name: grafana
        ports:
           - 3000:3000
        environment:
           - GF_SECURITY_ADMIN_PASSWORD=secret
        links:
          - prometheus-server:prometheus
 
